apiVersion: v1
kind: Namespace
metadata:
  name: devops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetes-arp-cleaner
rules:
- apiGroups: ['']
  resources: ['pods']
  verbs: ['get', 'list', 'watch']
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-arp-cleaner
  namespace: devops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-arp-cleaner
subjects:
- kind: ServiceAccount
  name: kubernetes-arp-cleaner
  namespace: devops
roleRef:
  kind: ClusterRole
  name: kubernetes-arp-cleaner
  apiGroup: rbac.authorization.k8s.io
